# Generated by Django 5.1.2 on 2024-11-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="remaining_tokens",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="total_tokens",
            field=models.IntegerField(default=100),
        ),
    ]
