# Generated by Django 5.1.2 on 2024-11-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_remaining_tokens_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="remaining_tokens",
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="total_tokens",
            field=models.IntegerField(default=1000),
        ),
    ]
