# Generated by Django 5.1.2 on 2024-10-30 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="assistant_response",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="tokens_used",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="user_message",
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("role", models.CharField(max_length=10)),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.conversation",
                    ),
                ),
            ],
        ),
    ]
